import { compilerContext } from "./compiler-context";

export function generateEnvCode() {
  const { adapter } = compilerContext.getContext();

  return `/// <reference types="xmcp" />

// Do not edit this file`;
}
